name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Replace with your desired branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./drumapppy  # Path to your app's folder
          push: true
          tags: judahsan/drum-machine:latest:1.0

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
